### PR TITLE
Add data source, dot syntax for server and fix crash when port is missing (fallback on the default port)

### PR DESCRIPTION
**Pull request by danylaporte**
Multiple fixes:

- Parse of `data source=` in AdoConfig which is the same as `server=`
- Support for dot syntax: `.` which is the same as `localhost`
- Fix crash when port is missing inside the server address. Fallback on the default port which are:
   - 1433 for std tcp connection
   - 1434 for resolving instances
   
 I have add tests to reflect the changes.

### CODE REVIEW

**Comment by pimeys** [comment]
Great. Btw, I have this PR for the ports I'd like to merge, so maybe rebase yours when I'm done and we'll merge this afterwards.

https://github.com/prisma/tiberius/pull/147

**Comment by danylaporte** [comment]
@pimeys Sure!

**Comment by danylaporte** [comment]
Can we merge this pull request?

**Comment by pimeys** [comment]
Can you rebase and fix conflicts? See also the default port handling that has changed in the master. You might want to change your pull request to adapt to those changes.

**Pull request merged**
