### PR TITLE
add fractional seconds precision for datetime2

### PR DESCRIPTION
**Pull request by tuplecats**
The solved problem described in issue #234

### CODE REVIEW

**Comment by pimeys** [comment]
Could we have some tests for this too so it will not break in the future.

**Comment by tuplecats** [comment]
I can write some tests.

PS. As I understood the datetime2 type from documentation. datetime2 has precision equal (7) by default. I tested the case, if there is a datetime2 field in the table without specifying the precision, and we pass datetime2(7) to INSERT BULK, then this will not cause an error.

**Comment by tuplecats** [comment]
Added time conversion of `DateTime2` to required "fractional seconds precision" parameter by column metadata.
Added tests.

All tests passed with features flags `tds73, chrono`.

**Comment by pimeys** [comment]
`cargo fmt` should fix the failing test.

**Comment by pimeys** [comment]
Thank you!

**Pull request merged**
