### PR TITLE
Add rustls

### LINKED ISSUE #65: Connecting to Azure SQL with tokio (on mac) gives a Tls connection closed via error.
this is my code

```rust
let mut config = Config::from_ado_string("server=xxx.database.windows.net,1433;UID=xxx;PWD=xxx;TrustServerCertificate=true")?;
let tcp = TcpStream::connect(config.get_addr()).await?;
tcp.set_nodelay(true)?;
let mut client = Client::connect(config, tcp.compat_write()).await.expect("Failed!");
```
and I get
```thread 'main' panicked at 'Failed!: Tls("connection closed via error")', src/main.rs:80:22```

### PR DESCRIPTION
**Pull request by esheppa**
* Allow users to choose either async-naitve-tls or async-tls to provide tls 
* Add testing for rustls to CI (appveyor only for now)
* Would be interesting to see if this can fix #65

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
As a quick note: we've been talking about merging `async-native-tls` into `async-tls` and allowing people to choose which TLS provider through there. We'd likely adopt the `async-native-tls` API for that. That might be a project that needs a bit more work than what's presented here, but that might be a different way to abstract over the two.

**Comment by pimeys** [comment]
I'm kind of ok with this. We could in Prisma for example enable this feature only for macOS. And thank you for the work!

**Comment by yoshuawuyts** [comment]
@esheppa what is missing from this PR still?

**Comment by esheppa** [comment]
Hi @yoshuawuyts - at the moment it seems to be stalling in the middle of the TLS handshake so I need to do a bit more debugging before I can change this out of draft status.

In terms of the `async-native-tls` and `async-tls` potential merge - are you looking for a PR for that or is it still in the design stage? If the former it may make sense for me to have a look at that first, and in the process I'll likely figure out what is going on with this branch as well. Otherwise it may be better for me to keep debugging in this branch until I can get it working.

**Comment by pimeys** [comment]
@esheppa I'd say keep debugging here, we can later move the code to the `async-tls` crate.

**Comment by pimeys** [comment]
I've been debugging this today a bit, and I found out a possible reason.

First some feature flags here https://github.com/esheppa/tiberius/pull/3

Then, I found out the difference between `async-native-tls` and `async-tls`. When we use the feature `tls`, we do `WRITE`, `FLUSH` and `READ`. Then switching to `rustls` flag, we go from `WRITE` directly to `READ`, which hangs forever (no data before flushing something to the wire first).

Now, this patch to asynct-tls should trigger a flush after writing, and makes us move forward:

```patch
diff --git a/src/rusttls/stream.rs b/src/rusttls/stream.rs
index 3b80a20..930dafd 100644
--- a/src/rusttls/stream.rs
+++ b/src/rusttls/stream.rs
@@ -89,6 +89,10 @@ impl<'a, IO: AsyncRead + AsyncWrite + Unpin, S: Session> Stream<'a, IO, S> {
         }
     }

+    fn complete_flush_io(&mut self, cx: &mut Context) -> Poll<io::Result<()>> {
+        Pin::new(self).poll_flush(cx)
+    }
+
     fn complete_inner_io(
         &mut self,
         cx: &mut Context,
@@ -112,6 +116,8 @@ impl<'a, IO: AsyncRead + AsyncWrite + Unpin, S: Session> Stream<'a, IO, S> {
                 }
             }

+            ready!(self.complete_flush_io(cx))?;
+
             if !self.eof && self.session.wants_read() {
                 match self.complete_read_io(cx) {
                     Poll::Ready(Ok(0)) => self.eof = true,

```

Now, when running the example:
```bash
env TIBERIUS_TEST_CONNECTION_STRING="user=SA;password=<YourStrong@Passw0rd>;server=tcp:localhost,1433;IntegratedSecurity=true;TrustServerCertificate=true;encrypt=true" cargo run --features rustls,tds73 --no-default-features --example async-std
```

We get a bit different output; still an error though...

```
   Compiling async-tls v0.10.0 (/home/pimeys/code/async-tls)
   Compiling tiberius v0.4.9 (/home/pimeys/code/tiberius)
    Finished dev [unoptimized + debuginfo] target(s) in 4.19s
     Running `target/debug/examples/async-std`
[src/tds/codec/pre_login.rs:37] (expected, self.encryption) = (
    Required,
    On,
)
[src/client/tls.rs:216] "WRITE" = "WRITE"
[src/client/tls.rs:230] "FLUSH" = "FLUSH"
[src/client/tls.rs:144] "READ" = "READ"
[src/client/tls.rs:164] Poll::Pending = Pending
[src/client/tls.rs:230] "FLUSH" = "FLUSH"
[src/client/tls.rs:144] "READ" = "READ"
[src/client/tls.rs:216] "WRITE" = "WRITE"
Error: An error occured during the attempt of performing I/O: invalid certificate: BadDER
```

**Comment by esheppa** [comment]
Thanks @pimeys - I've also added some changes suggsted from `webpki` and `rustls` github issues where we desire to avoid server host checking (eg TrustServerCert=true). 

In the case of the self-signed certs in the mssql container - I think the issue is that they don't have the `SAN` defined. One workaround is here: https://github.com/ctz/rustls/issues/373 - however it may be better for us to document that all certificates used when enabling `rustls` have to be structured appropriately. The decision here probably depends on our interpretation of `TrustServerCert`.

Below is a run of the `examples/tokio.rs` connecting to Azure SQL (Azure SQL only allows `TrustServerCert=false;Encrypt=true`). 

It looks like the server is rejecting part way through the tls handshake, so there might be something incompatible or potentially we need to stop encapsulating the packets in `PRELOGIN` at a different stage with `rustls`. I'll keep experimenting for now.

```
Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/tokio`
[src/tds/codec/pre_login.rs:37] (expected, self.encryption) = (
    Required,
    On,
)
[2020-10-04T02:16:55Z INFO  tiberius::client::connection] Performing a TLS handshake 
[2020-10-04T02:16:55Z DEBUG rustls::anchors] add_pem_file processed 2 valid and 0 invalid certs
[2020-10-04T02:16:55Z DEBUG rustls::client::hs] No cached session for DNSNameRef("<redacted>.database.windows.net")
[2020-10-04T02:16:55Z DEBUG rustls::client::hs] Not resuming any session
[src/client/tls.rs:217] "WRITE" = "WRITE"
[src/client/tls.rs:231] "FLUSH" = "FLUSH"
[src/client/tls.rs:144] "READ" = "READ"
[src/client/tls.rs:164] Poll::Pending = Pending
[src/client/tls.rs:231] "FLUSH" = "FLUSH"
[src/client/tls.rs:144] "READ" = "READ"
[src/client/tls.rs:164] Poll::Pending = Pending
[src/client/tls.rs:231] "FLUSH" = "FLUSH"
[src/client/tls.rs:144] "READ" = "READ"
[src/client/tls.rs:164] Poll::Pending = Pending
[src/client/tls.rs:231] "FLUSH" = "FLUSH"
[src/client/tls.rs:144] "READ" = "READ"
[src/client/tls.rs:204] &read = 4088
[src/client/tls.rs:231] "FLUSH" = "FLUSH"
[src/client/tls.rs:144] "READ" = "READ"
[src/client/tls.rs:204] &read = 2234
[2020-10-04T02:16:55Z DEBUG rustls::client::hs] ALPN protocol is None
[2020-10-04T02:16:55Z DEBUG rustls::client::hs] Using ciphersuite TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
[2020-10-04T02:16:55Z DEBUG rustls::client::hs] Server may staple OCSP response
[2020-10-04T02:16:55Z DEBUG rustls::client::tls12] ECDHE curve is ECParameters { curve_type: NamedCurve, named_group: secp256r1 }
[2020-10-04T02:16:55Z DEBUG rustls::client::tls12] Server DNS name is DNSName("<redacted>.database.windows.net")
[src/client/tls.rs:217] "WRITE" = "WRITE"
[src/client/tls.rs:217] "WRITE" = "WRITE"
[src/client/tls.rs:217] "WRITE" = "WRITE"
[src/client/tls.rs:231] "FLUSH" = "FLUSH"
[src/client/tls.rs:144] "READ" = "READ"
Error: An error occured during the attempt of performing I/O: tls handshake eof
```

**Comment by pimeys** [comment]
Hey @esheppa, did you get anywhere with this?

**Comment by esheppa** [comment]
Hi @pimeys  - I'm thinking of trying this out with `tokio-rustls` and then if that works see if I can find any differences between that and `async-rustls` that might be incompatible with how SQL server is expecting the handshake to go.

**Comment by pimeys** [comment]
We could also consider having an option to compile against openssl on macOS, if this doesn't work out. Although that work sounds pretty horrible to me, so hopefully rustls solves the issues...

**Comment by esheppa** [comment]
Hi @pimeys - I've tried this out with tokio-rustls as well and haven't been able to get it working. Will close for now.

**Pull request closed without merging**
