### PR TITLE
enable rustls for TLS

### PR DESCRIPTION
**Pull request by rogerpengyu**
replace the native TLS lib with rustls

### CODE REVIEW

**Comment by pimeys** [comment]
Hmm. Why the Github actions don't even try to start here...

**Comment by rogerpengyu** [comment]
> Hmm. Why the Github actions don't even try to start here...

There is a conflict. I will resolve it

**Comment by rogerpengyu** [comment]
conflict resolved

**Comment by pimeys** [comment]
Here's a few changes to the PR from me: https://github.com/rogerpengyu/tiberius/pull/3

There's a failure in the Windows tests using the named instance. I think we do not set the hostname in the TLS handshake wrong in these situations...

**Comment by pimeys** [comment]
To me this looks like we cannot test at all on Windows, it fails to that error on connection.

**Comment by pimeys** [comment]
If we get the Windows tests green, this is ready to be merged.

**Comment by rogerpengyu** [comment]
I should get some time within this week for this.

**Comment by rogerpengyu** [comment]
> To me this looks like we cannot test at all on Windows, it fails to that error on connection. Seems to not like that we connect to `127.0.0.1` on Windows; it wants a real DNS name...

this is trickier than I thought. seems rustls not supporting IP addresses is a well-known pain point: https://github.com/rustls/rustls/issues/184

Other than the test case here (connect to localhost), is supporting IP addresss or localhost a must-have feature for tiberius?

**Comment by pimeys** [comment]
I think it is a huge breaking change that might lead to a pile of issues if enforced...

Also it seems the tests are not working on Windows if using localhost instead of an IP. Something rustls does not like about the windows version of SQL Server.

**Comment by rogerpengyu** [comment]
the localhost is only used with trustAll, in which case SNI is not enabled. Just put a place holder in this case, see if it works

**Comment by pimeys** [comment]
One option would be to have a compilation flag between opentls and rustls crates. Then this PR could be mainlined and the user could choose between openssl and rustls.

**Comment by rogerpengyu** [comment]
I tried the placeholder solution (in case of local host + trust server cert situation, just provide a placeholder domain name. As SNI is not enabled so the domain name is not used any way). It worked with my local setup. Will look into why the test failed.

**Comment by rogerpengyu** [comment]
fixed one warning. need one more approval to run test

**Comment by rogerpengyu** [comment]
the only failed test is format test now. use rustfmt check success on the file

**Comment by rogerpengyu** [comment]
need one more approval to run the workflow

**Comment by pimeys** [comment]
Yes, I'm on it as soon as we have our release done and things calm down a bit. Not time right now, let's see tomorrow!

**Comment by pimeys** [comment]
Wanted to cut down some dependencies, so I made a new PR adding my commit to the top. Merging today hopefully...

**Pull request closed without merging**
