### PR TITLE
create a feature flag for rustls integration

### PR DESCRIPTION
**Pull request by rogerpengyu**
based on the feedback, enable rustls under a feature use_rustls

### CODE REVIEW

**Comment by rogerpengyu** [comment]
waiting for approval to trigger the workflow is painful :(

**Comment by pimeys** [comment]
Yeah. When this gets merged the next PR will not need an approval. I don't really want to have the actions available for every PR because soon there will be bots triggering bitcoin miners and eating all CI minutes.

**Comment by rogerpengyu** [comment]
All tests passed. Waiting for approval

**Comment by rogerpengyu** [comment]
could this be merged? Or any more suggestions?

**Comment by pimeys** [comment]
I want to do a couple of things here, but merging it for now and doing them in separate PR to get you to the contributors list and you can use the CI more easily after that.

Thank you for the work!

**Pull request merged**
